# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: 'install'
    customRegistry: 'useFeed'
    customFeed: '48677b75-556d-43f3-8987-08b23982bcd4/bf5b94ab-fba6-47fc-b115-1b356c516232'

- script: |
    npm run build
  displayName: 'npm install and build'

- task: WhiteSource Bolt@20
  inputs:
    cwd: '${System.DefaultWoringDirectory}'